### PR TITLE
Add @racahsum macro

### PR DESCRIPTION
**Pull request by sostock**
This implements the \@racahsum macro.

### CODE REVIEW

**Comment by mortenpi** [comment]
:wave: I am passively following the development of JAC. I hope you don't mind some unsolicited comments :slightly_smiling_face: 

I noticed the work on half-integers, CG coefficients and Wigner symbols. Just in case you missed it, the [WignerSymbols](https://github.com/Jutho/WignerSymbols.jl) package has the j-symbols, CG coefficients and a `HalfInteger` type implemented. It looks like you may have some additional features, which would probably be great to have upstreamed as well, but I think there is quite a bit of code that could be shared.

**Comment by sostock** [comment]
@mortenpi Of course your comments are welcome.

The code for `HalfInt`/CG coefficients/Wigner symbols in this PR is a simplified version of code that I wrote for my own (private) programs some time ago. I decided to use the Wigner symbols from GSL.jl instead of WignerSymbols.jl because the latter does not have a function for the 9j-symbol.

Regarding `HalfInt`/`HalfInteger`, I agree that some (probably most) code could be shared. I had actually planned to publish a more comprehensive version of the `HalfInt` code as a separate package (providing a `Half{T<:Integer}` type for `HalfInteger`s based on integer types of different size). I plan to upload a first version of that code within the next couple of days and would suggest that we talk about how to proceed from there.

**Comment by mortenpi** [comment]
Ah, I didn't look at the code that closely. It would be interesting to know how the performance and accuracy compare between WignerSymbols and GSL.

With @jutho we were also wondering whether it might be worth splitting the HalfInteger functionality out of WignerSymbols. A generic `HalfInteger{<:Integer}` / `Half{<:Integer}` would indeed be a good way to approach this I think. And you could then also have `const HalfInt64 = HalfInteger{Int64}` etc. Feel free to ping me when you have the code up :slightly_smiling_face:

**Comment by sostock** [comment]
@mortenpi I have now uploaded a first version of the HalfIntegers package: https://github.com/sostock/HalfIntegers.jl

I will probably make some minor changes and write a more detailed documentation before I register the package. Feel free to comment on the code.

**Comment by Jutho** [comment]
Look's great already. Keep me informed when you plan to register this; I'd be happy to make the switch.

**Pull request merged**
